mod

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -26,6 +26,7 @@ _webapp_runner() {
 }
 
 echo "---"
+[ -f /TestApp-0.0.1-SNAPSHOT.jar ] && echo "Found jar file 1111" || echo "Not foundjar file 1111"
 if [ ! -f $BUILD_DIR/Procfile ]; then
     default_process_types:
       web: java -Dserver.port=\$PORT \$JAVA_OPTS -jar /TestApp-0.0.1-SNAPSHOT.jar
